services:
  backend:
    build: .
    container_name: questify-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${HIBERNATE_DDL_AUTO}
      - SPRING_JPA_DATABASE_PLATFORM=${JPA_DATABASE_PLATFORM}
    volumes:
      - questify_data:/app/data
    networks:
      - questify-network
  postgres:
    image: postgres:16-alpine
    container_name: questify-postgres
    environment:
      POSTGRES_DB: questify
      POSTGRES_USER: questify
      POSTGRES_PASSWORD: questify
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U questify"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  questify_data:
  postgres_data:

networks:
  questify-network:
    driver: bridge 