services:
  backend:
    build: .
    container_name: questify-backend
    ports:
      - "3000:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/questify
      - SPRING_DATASOURCE_USERNAME=questify
      - SPRING_DATASOURCE_PASSWORD=questify
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    volumes:
      - questify_data:/app/data
    networks:
      - questify-network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: questify-postgres
    environment:
      POSTGRES_DB: questify
      POSTGRES_USER: questify
      POSTGRES_PASSWORD: questify
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - questify-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U questify"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  questify_data:
  postgres_data:

networks:
  questify-network:
    driver: bridge 